services:
  postgres:
    image: postgres:15
    container_name: ticket-booking-db
    restart: always
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
    ports:
      - '5433:5432'   # host:container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - ticket-booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: ticket-booking-redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - ticket-booking-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: docker/DockerFile.api
    container_name: ticket-booking-api
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}"
      REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}"
    ports:
      - "${PORT}:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ticket-booking-network

  worker:
    build:
      context: .
      dockerfile: docker/DockerFile.worker
    container_name: ticket-booking-worker
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSLMODE}"
      REDIS_URL: "redis://${REDIS_HOST}:${REDIS_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ticket-booking-network

networks:
  ticket-booking-network:
    driver: bridge
