#Docker 
version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: ticket-booking-db
    restart: always
    environment:
      POSTGRES_USER: "ticket"
      POSTGRES_PASSWORD: "ticket123"
      POSTGRES_DB: "ticket_db"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
